name: cint pipeline

on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Compile
        run: |
          env
          cmake -DWITH_CINT2_INTERFACE=1 -DWITH_RANGE_COULOMB=1 -DWITH_COULOMB_ERF=1 -DWITH_F12=1 -DWITH_4C1E=1 -Bbuild -DKEEP_GOING=1 .
          cmake --build build
          pip install numpy mpmath pyscf
      - name: Test for rys-roots
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd ${{ github.workspace }}/testsuite
          python test_rys_roots.py
      - name: Unittest
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd ${{ github.workspace }}/testsuite
          python test_cint.py --quick
          python test_3c2e.py --quick
          python test_cart2sph.py
          python test_c2s.py
          python test_cint4c1e.py
          python test_int1e.py
          python test_int1e_grids.py
          python test_int2c2e.py
          python test_int3c1e.py
          python test_int2e.py --quick
